services:
  - type: web
    name: symphony-music-ai
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: FLASK_DEBUG
        value: "0"
